# load asdf plugins
- asdf:
    - plugin: helm
      url: https://github.com/Antiarchitect/asdf-helm.git
      global: 3.14.0
      versions:
        - 3.14.0
    - plugin: kubectl
      url: https://github.com/asdf-community/asdf-kubectl.git
      global: 1.30.2
      versions:
        - 1.30.2
    - plugin: gradle
      url: https://github.com/rfrancis/asdf-gradle.git
      global: 8.8
      versions:
        - 8.8
    - plugin: java
      url: https://github.com/halcyon/asdf-java.git
      global: corretto-17.0.11.9.1
      versions:
        - corretto-17.0.11.9.1
    - plugin: kotlin
      url: https://github.com/asdf-community/asdf-kotlin.git
      global: 2.0.0
      versions:
        - 2.0.0
        - 1.9.24
    - plugin: maven
      url: https://github.com/Proemion/asdf-maven.git
      global: 3.9.8
      versions:
        - 3.9.8
    - plugin: nodejs
      url: https://github.com/asdf-vm/asdf-nodejs.git
      global: 20.9.0
      versions:
        - 20.9.0
