- link:
    # homebrew
    ~/Brewfile: configs/homebrew/Brewfile

- shell:
    - command: cd ~/ && brew bundle install
      description: Installing brew bundles
      stdout: true
    # - command: brew cu -a -y
    #   description: Updating brew cask dependencies
    #   stdout: true
    - command: cd ~/ && brew update && brew upgrade
      description: Updating brew dependencies
      stdout: true
