- create:
    - ~/.config/git-hooks

- link:
    # git configurations
    # inspired by: https://kurtmckee.org/2022/06/managing-your-git-config-using-dotbot/
    ~/.gitignore: configs/git/gitignore
    ~/.gitconfig: configs/git/gitconfig.ini
    ~/.gitmessage: configs/git/gitmessage
    ~/.gitconfig-privatespace:
        path: configs/git/gitconfig-privatespace.ini
    ~/.gitconfig-workspace:
        path: configs/git/gitconfig-workspace.ini
        if: '[ -f configs/git/gitconfig-workspace.ini ]'
    ~/.gitconfig-platform-specific:
        if: '[ `uname` = "Darwin" ]'
        path: configs/git/platform/wsl.ini
        ignore-missing: true
        relink: true
    ~/.gitconfig-platform-specific:
        if: 'uname -a | grep -q "WSL2"'
        path: configs/git/platform/wsl.ini
        ignore-missing: true
        relink: true
    # git-hooks
    ~/.config/git-hooks/:
        path: configs/git/hooks/*
        glob: true

- shell:
    - command: |
        if ! command -v keychain &> /dev/null; then
          if uname -a | grep -q "WSL2"; then
            sudo apt-get install keychain
          fi
        fi
