- link:
    ~/.config/k3d/:
      path: configs/k3d/**
      glob: true
      relink: true
      create: true

- shell:
    - command: command -v k3d
      description: Verify that k3d is installed
      stdout: true
    - command: command -v kubectl
      description: Verify that kubectl is installed
      stdout: true
    # - command: k3d cluster create --config ~/.config/k3d/cluster-config.yml
    #   description: Create local cluster
    #   stdout: true
    # - command: kubectl config use-context k3d-local-cluster
    #   description: Ensure the kubectl config is up to date
    # - command: kubectl -n default apply -f ~/.config/k3d/admin-user.yml
