- link:
    ~/AppData/Roaming/Code/User/settings.json:
      path: configs/vscode/settings.json
      force: true

- shell:
  - command: "sh C:/Users/anderski1/dotfiles/configs/vscode/install-extensions.sh"
    description: Updating VSCode Extensions
    stdout: true
    stdin: true
