- link:
    ~/Library/Application Support/Code/User/settings.json:
      path: configs/vscode/settings.json
      force: true

- shell:
    - command: "sh ~/dotfiles/configs/vscode/install-extensions.sh"
      description: Updating VSCode Extensions
      stdout: true
      stdin: true
