- create:
    - ~/.config

- link:
    # zsh configurations
    ~/.config/aliases.zsh: configs/zsh/aliases.zsh
    ~/.config/functions.zsh: configs/zsh/functions.zsh
    ~/.zshenv:
        ignore-missing: true
        path: configs/zsh/.zshenv
    ~/.zshrc: configs/zsh/.zshrc
