- create:
    - ~/.config
    - ~/.config/zsh
    - ~/.config/zsh/autocomplete
    - ~/.config/zsh/functions

- link:
    # main configs
    ~/.zshrc: configs/zsh/zshrc
    ~/.zshenv: configs/zsh/zshenv
    ~/.ssh/config: configs/zsh/_ssh_config
    # sub-configs
    ~/.config/zsh/aliases.zsh: configs/zsh/_aliases.zsh
    ~/.config/zsh/functions.zsh: configs/zsh/_functions.zsh
    ~/.config/zsh/functions/github.zsh: configs/zsh/functions/_github.zsh
    ~/.config/zsh/functions/helm.zsh: configs/zsh/functions/_helm.zsh
    ~/.config/zsh/functions/init.zsh: configs/zsh/functions/_init.zsh
    ~/.config/zsh/functions/kubectl.zsh: configs/zsh/functions/_kubectl.zsh
    ~/.config/zsh/functions/navigation.zsh: configs/zsh/functions/_navigation.zsh
    ~/.config/zsh/wsl.zsh:
        if: 'uname -a | grep -q "WSL2"'
        path: configs/zsh/_wsl.zsh
    ~/.config/zsh/mac.zsh:
        if: '[ `uname` = "Darwin" ]'
        path: configs/zsh/_mac.zsh
    # starship
    ~/.config/starship.toml: configs/zsh/starship.toml
    ~/.config/zsh/starship.zsh: configs/zsh/_starship.zsh
    # autocomplete
    ~/.config/zsh/autocomplete/kubectl: configs/zsh/autocomplete/_kubectl

- shell:
    - command: |
        if ! command -v "zsh" >/dev/null 2>&1; then
            sudo apt update && sudo apt install zsh -y
        fi
      description: Installing zsh
      stdout: true
    - command: sudo chsh -s $(which zsh) $(whoami)
      description: Setting default shell to zsh
      stdout: true
    - command: source ~/.zshrc
      description: Source the zshrc file
      stdout: true
