#!/usr/bin/env bash

set -e

sudo apt-get update && sudo apt-get install build-essential procps curl file git

if test ! $(which brew); then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! $(command -v brew &>/dev/null); then
    # Install homebrew
    (
        echo
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    ) >>/home/$USER/.profile
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    source $HOME/.profile
fi

mkdir -p ~/.gnupg # Create the gpg directory before running the installer

[ -d ~/dotfiles ] || git clone https://github.com/johannes-gs/dotfiles.git ~/dotfiles
[ -d ~/dotfiles ] && (cd ~/dotfiles && git submodule update --init --recursive)

echo "Finished setting up your WSL2 environment 🎂"
