#!/usr/bin/env zsh

# Custom env
[ -f ~/.config/zsh/secrets.zsh ] && source ~/.config/zsh/secrets.zsh

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Krew (k8s plugin manager)
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
