#!/usr/bin/env zsh

# Preferred editor for local and remote sessions
export EDITOR='vim'

# https://github.com/keybase/keybase-issues/issues/2798
export GPG_TTY=$(tty)

# Krew (k8s plugin manager)
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Elhub-plat-utils
export PATH="$HOME/github/plat-platform-utils/scripts:$PATH"

# Add ~/.local/bin to PATH
export PATH="$HOME/.local/bin:$PATH"

# Add Jetbrains Toolbox apps to PATH
export PATH="$HOME/.local/share/JetBrains/Toolbox/scripts:$PATH"
